package com.example.FreshGreen.service;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.example.FreshGreen.model.FGcart;
import com.example.FreshGreen.model.FGproduct;
import com.example.FreshGreen.repository.CartRepository;

@Service
public class CartService {

    @Autowired
    private CartRepository repository;

    //private final List<FGcart> cart = new ArrayList<>();

    public String addToCart(FGproduct product, int quantity) {
        try {
            return repository.save(new FGcart(
                null, // ID will be generated by the database
                product.getProductName(),
                quantity,
                product.getProductPrice() * quantity
            )) != null ? "Item added to cart successfully." : "Failed to add item to cart.";
        } catch (Exception e) {
            return e.getMessage();
        }
    }

    public List<FGcart> getCartItems() {
        return repository.findAll();
    }

    public void clearCart(Long id) {
        repository.deleteById(id);
    }
}
